# Generated by Django 4.2.8 on 2023-12-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='requests',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('apartment', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=500)),
                ('date', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tenant',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('date_in', models.CharField(max_length=100)),
                ('date_out', models.CharField(max_length=100)),
                ('apartment', models.CharField(max_length=100)),
            ],
        ),
    ]
